<a href="https://colab.research.google.com/github/vinayastar01/deep-learning-2025/blob/main/0_day_tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
tensor = tf.constant([[10,5],[8,9]])


In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  5],
       [ 8,  9]], dtype=int32)>

In [ ]:
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 15],
       [18, 19]], dtype=int32)>

In [ ]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [ 80,  90]], dtype=int32)>

In [ ]:
tensor*10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  50],
       [ 80,  90]], dtype=int32)>

In [ ]:
tensor2 = tf.constant([[2,3,5],[5,5,6],[6,8,4]])

In [ ]:
tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[2, 3, 5],
       [5, 5, 6],
       [6, 8, 4]], dtype=int32)>

In [ ]:
tensor2 @ tensor2

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [4,2], In[1]: [4,2] [Op:MatMul] name: 

In [ ]:
dot = tf.matmul(tensor2,tensor2)
print(dot)

tf.Tensor(
[[49 61 48]
 [71 88 79]
 [76 90 94]], shape=(3, 3), dtype=int32)


In [ ]:
tensor2 @ tensor2

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[49, 61, 48],
       [71, 88, 79],
       [76, 90, 94]], dtype=int32)>

In [ ]:
tf.transpose(dot
             )

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[49, 71, 76],
       [61, 88, 90],
       [48, 79, 94]], dtype=int32)>

In [ ]:
tf.tensordot(tensor2,tf.transpose(tensor2),axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 38,  55,  56],
       [ 55,  86,  94],
       [ 56,  94, 116]], dtype=int32)>

In [ ]:
tensor3 = tf.constant([[3,4,4],[4,5,3]])

In [ ]:
tensor3

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 4, 4],
       [4, 5, 3]], dtype=int32)>

In [ ]:
tf.reshape(tensor3,shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[3, 4],
       [4, 4],
       [5, 3]], dtype=int32)>

In [ ]:
import numpy as np


In [ ]:
A = tf.constant(np.random.randint(0,100,size=50))
A

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([27, 93, 66, 83, 37, 11, 15, 33, 16, 46,  4, 48, 46, 27, 94, 68, 12,
        9, 96, 57, 46, 60, 99, 21, 41,  1, 67, 45, 39,  4, 79, 38, 59, 35,
       18, 77, 39, 88,  8, 48, 39, 37, 63, 34, 46, 92, 47, 46, 26, 59])>

In [ ]:
tf.reduce_min(A)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.reduce_max(A)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(A
               )

<tf.Tensor: shape=(), dtype=int64, numpy=45>

In [ ]:
import tensorflow_probability as tfp

tfp.stats.variance(A)

<tf.Tensor: shape=(), dtype=int64, numpy=707>

In [ ]:
tf.math.reduce_std(tf.cast(A,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.596458435058594>